#!/var/lang/node20/bin/node
const fs = require('fs');
const path = require('path');

const targetDb = '/tmp/dev.db';

// 2. 设置环境变量并启动
process.env.DATABASE_URL = `file:${targetDb}`;
process.env.PORT = '9000';
require('./server.js');
